// practice2/react_cnode/src/components/UserInfo.js
import React, { Component } from 'react'
import { formatDate } from './filters'
import { Link } from 'react-router-dom'
import '../styles/UserInfo.css'
import GetData from'./Data'

export default class UserInfo extends Component {
  constructor(props){
    super(props)
    this.state = {
      userinfo:{
        recent_replies:[], //初始化第一次渲染时,异步数据返回之前，这几个数据是undefined，下面map会报错，故给个初始值［］就好
        recent_topics:[]
      },
      laoding: true //加载动画
    }
    this.reqUser()
  }

  render(){
    return(
      <div className='UserInfo'>
        {
          this.state.loading === true ? 
          <div className='loading'>
            <img src={require('./static/loading.gif')} />
          </div> 
          : 
          <div className='userInformation'>
            <section>
              <img src={this.state.userinfo.avatar_url} />
              <span>{this.state.userinfo.loginname}</span>
              <p>{this.state.userinfo.score}积分</p>
              <p>注册时间：{ formatDate(this.state.userinfo.create_at) }</p>
            </section>

            <div className='replies'>
              <p>回复的主题</p>
              <ul>
                {/* 点击文章并跳转 */}
                {
                  this.state.userinfo.recent_replies.map((item)=>{
                    return (
                      <li key={item.id}>
                        <Link to={`/topic/${item.id}&author=${this.props.match.params.name}`} >{item.title}</Link>
                      </li>
                    )
                  })
                }
              </ul>
            </div>

            <div className='topics'>
                <p>创建的主题</p>
                <ul>
                  {
                    this.state.userinfo.recent_topics.map((item)=>{
                      return (
                        <li key={item.id}>
                          <Link to={`/topic/${item.id}&author=${this.props.match.params.name}`} >{item.title}</Link>
                        </li>
                      )
                    })
                  }
                </ul>
            </div>
          </div>
        }
      </div>
    )
  }

  reqUser(){
    //请求数据，参数是App.js中的Route所接收，由SideBar.js中的Link发送
    GetData(`https://cnodejs.org/api/v1/user/${this.props.match.params.name}`, {}, (res)=>{            
      this.setState({
        userinfo: res.data.data,
        loading: false //加载动画停止
      })
    })
  }

}

// practice/VueCourse/第12课_cnode社区/cnode/src/components/UserInfo.vue
<template>
  <div class="UserInfo">
    <!-- 如果正在加载 显示此div -->
    <div class="loading" v-if="isLoading">
      <img src="../assets/loading.gif" />
    </div>
    <div class="userInformation" v-else>
      <section>
        <img :src="userinfo.avatar_url" />
        <span>{{userinfo.loginname}}</span>
        <p>{{userinfo.score}}积分</p>
        <p>注册时间: {{userinfo.create_at | formatDate}}</p>
      </section>
      <div class="replies">
        <p>回复的主题</p>
        <ul>
          <!-- 点击文章并跳转 -->
          <li v-for="(item, key) in userinfo.recent_replies" :key="key"><!-- key和:key就是为了防止报错 -->
            <router-link :to="{
              name:'post_content',//路由名称，是Article组件
              params:{
                id:item.id //路由参数为 文章id, userinfo是该组件的data
              }
            }">
              {{item.title}}
            </router-link>
          </li>
        </ul>
      </div>
      <div class="topics">
        <p>创建的主题</p>
        <ul>
          <li v-for="(item, key) in userinfo.recent_topics" :key="key"><!-- key和:key就是为了防止报错 -->
            <router-link :to="{
              name:'post_content',//路由名称，是Article组件
              params:{
                id:item.id //路由参数为 文章id
              }
            }">
              {{item.title}}
            </router-link>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "UserInfo",
  data() {
    return {
      isLoading: false,
      userinfo: {}
    };
  },
  methods: {
    getData() {//Axios，查询 用户的信息
      this.$http.get(`https://cnodejs.org/api/v1/user/${this.$route.params.name}`) //该组件读取 它所属的路由中 的参数
        .then(res => {
          this.isLoading = false; //加载成功后，去除 加载动画
          this.userinfo = res.data.data; //返回的数据json格式中有data属性下的data属性
          //console.log(this.userinfo)
        })
        .catch(function(err) {
          console.log(err);
        });
    }
  },
  beforeMount(){
    this.isLoading=true //加载成功之前 显示加载动画
    this.getData() //在页面加载之前 获取数据
  }
};
</script>

<style scoped>
.userInfomation {
  background: white;
  width: 75%;
  margin: 10px auto;
}
.userInfomation section {
  padding: 12px;
}
.userInfomation img {
  width: 30px;
}
.userInfomation li {
  list-style: none;
}
.userInfomation .replies,
.userInfomation .topics {
  font-size: 0.72rem;
  border-top: 10px #dddddd solid;
}
.userInfomation > div > p {
  padding: 12px 0 12px 12px;
  background-color: rgba(212, 205, 205, 0.17);
  font-size: 0.75rem;
  margin: 0;
}
.userInfomation > div > ul > li {
  padding: 4px 0 4px 12px;
  white-space: nowrap;
  font-size: 0.72rem;
  text-overflow: ellipsis;
  overflow: hidden;
  line-height: 30px;
  vertical-align: middle;
}
.userInfomation > div > ul > li > a {
  color: #094e99;
  text-decoration: none;
}
</style>
